### ISSUE TITLE
npm installs stream-serializer@1.0.0 dependency instead of latest

### ISSUE THREAD

**Issue by ghost** [dominictarr/rpc-stream#19]
When I run `npm install rpc-stream` I can see that it installs `stream-serializer@1.0.0`. Is that what you intended?

Looking at the changelist of [stream-serializer](https://github.com/dominictarr/stream-serializer), it looks like the latest `v1.1.2` should be compatible with `rpc-stream`.

**Comment by dominictarr** [comment]
Yeah probably it works, but just doesn't depend on the feature introduced
in 1.1
Is this causing a problem?

**Comment by ghost** [comment]
No problems, just putting it out there since I saw some bugs fixed since 1.0. Now I see that those were bugs with a new feature. Thanks.
