### ISSUE TITLE
EPIPE and ECONNRESET

### ISSUE THREAD

**Issue by Aminelahlou** [dominictarr/rpc-stream#20]
Hello I am getting this error once every 2 days, I think it might be too many connections at the same time, but I don't really know, how can I check if it is really too many connections, and how can I fix the bug?
Thanks in advance
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

**Comment by dominictarr** [comment]
this error is about tcp, not about rpc-stream. maybe the server you are connecting to is crashing, or otherwise the network is going down. I'd start with google search for ECONNRESET
